# TODO: Change directory after #22

version: 2
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Frontend/my-app/"
    schedule:
      interval: "weekly"
