name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # workflow_dispatch:

env:
  AWS_REGION: us-east-1 # TODO: Does this need the f? 
  AWS_INSTANCE_SG_ID: ${{ secrets.AWS_SECRTITY_GROUP_ID }}
# permissions:
#   contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    # strategy:
    #   matrix:
    #     node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SSH_PRIVATE_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get runner ip address
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Whitelist runner ip address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Copy repo to EC2 instance
        run: |
          touch test
      
      - name: revoke runner ip address
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
          

    #   - name: Login to Amazon 

      # - name: rsync deployments
      #   uses: burnett01/rsync-deployments@5.1
      #   with:
      #     switches: -avzr --delete
      #     path: ./*
      #     remote_path: /var/www/jjernstrom/
      #     remote_host: ec2-18-207-136-229.compute-1.amazonaws.com
      #     remote_user: ec2-user
      #     remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      
    # - uses: actions/checkout@v4
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    # - run: npm ci
    # - run: npm run build
    # - run: npm test
