name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_INSTANCE_SG_ID: ${{ secrets.AWS_SECRTITY_GROUP_ID }}

# Enable action to create JWT for AWS credentials
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    # strategy:
    #   matrix:
    #     node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::445567072000:role/OIDC-GitHub--EC2-deployment
          role-session-name: EC2-Deployment

      - name: Deploy with rsync
        run: sudo rsync -v ./ ${{ secrets.DEST }}

