name: Production Deployment

on:
  push:
    branches: [ main ]

# Enable action to create JWT for AWS credentials
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.PROD_DEPLOY_ROLE }}
          role-session-name: OIDCSession

      - name: Build Docker Image
        run: |
          cd rogue-vivarium && \
          docker build -t rogueVivarium:dev . && \
          docker save -o rogueVivarium-dev.tar rogueVivarium:dev 

      - name: Deploy to S3 Production
        run: aws s3 cp rogue-vivarium/rogueVivarium-dev.tar s3://jjernstrom-s3-prod/rogueVivarium-dev.tar
